Ps 5044 5 7 binlog decryption
laurynas-biveinis/percona-server pull request #24
Opened 2019-02-14 08:22 UTC by robgolebiowski

Still need to make it build on centos + clang formatting.

2019-02-14 12:32 UTC, laurynas-biveinis requested changes
Looks great, minor comments only.
One question is, what is the goal with MTR?

2019-02-14 12:32 UTC, laurynas-biveinis commented on mysql-test/mysql-test-run.pl
> +"main,sys_vars,binlog,binlog_gtid,binlog_nogtid,percona_binlog_5_7_decryption,federated,gis,rpl,rpl_gtid,rpl_nogtid,innodb,innodb_gis,innodb_fts,innodb_zip,innodb_undo,perfschema,funcs_1,opt_trace,pa
TODO The suite needs a shorter name

2019-02-14 12:32 UTC, laurynas-biveinis commented on sql/binlog_reader.cc
> +      m_number_of_events_with_half_the_size = 0;
Spurious?

2019-02-14 12:32 UTC, laurynas-biveinis commented on sql/event_crypt.h
> +// 5.7 event decrypted
"Decrypt Percona binlog encryption encrypted-events" or similar

2019-02-14 12:32 UTC, laurynas-biveinis commented on sql/log_event.cc
> +  my_b_printf(head, "\n# The rest of the binlog is encrypted with PS 5.7 encryption!\n");
Spell out Percona Server

2019-02-14 12:32 UTC, laurynas-biveinis commented on sql/log_event.cc
> +    my_b_printf(&print_event_info->head_cache, "\n# %s", "Event encrypted with 5.7 PS binlog encryption\n");
Spell out Percona Server

2019-02-15 12:29 UTC, robgolebiowski commented
https://ps2.cd.percona.com/view/8.0/job/percona-server-8.0-param/52/

2019-03-01 10:13 UTC, closed without merging